//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicCharge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BasicCharge()
        {
            this.RentalAgreements = new HashSet<RentalAgreement>();
        }
    
        public int BasicChargesId { get; set; }
        public Nullable<int> HPkr { get; set; }
        public Nullable<int> KPkr { get; set; }
        public Nullable<int> DPkr { get; set; }
        public Nullable<int> TollTaxCharges { get; set; }
        public Nullable<int> DamageIfAny { get; set; }
        public Nullable<int> GST { get; set; }
        public Nullable<int> DriverCharges { get; set; }
        public Nullable<int> TotalCharges { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalAgreement> RentalAgreements { get; set; }
    }
}
