//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public string ClientFlightNo { get; set; }
        public string ClientPickUpAddress { get; set; }
        public string ClientContactNo { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
