//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalAgreement
    {
        public int RentalAgreementId { get; set; }
        public string AcutalItinerary { get; set; }
        public Nullable<int> BasicChargesId { get; set; }
        public Nullable<int> ReservationId { get; set; }
    
        public virtual BasicCharge BasicCharge { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
