//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalAgreement
    {
        public int Id { get; set; }
        public int Reservation_Id { get; set; }
        public string Actual_Tinerary { get; set; }
        public Nullable<int> Rs_Per_Hour { get; set; }
        public Nullable<int> Rs_Per_Day { get; set; }
        public Nullable<int> Rs_Per_Km { get; set; }
        public Nullable<int> Toll_Tax_Charges { get; set; }
        public Nullable<int> Drive_Charges { get; set; }
        public Nullable<int> Fuel_Charges { get; set; }
        public Nullable<int> GST { get; set; }
        public Nullable<byte> Is_Agreement_Completed { get; set; }
        public Nullable<int> Pre_Payment { get; set; }
        public Nullable<int> Payment_Due { get; set; }
        public Nullable<int> Km_In { get; set; }
        public Nullable<int> Km_Out { get; set; }
        public Nullable<System.DateTime> Time_In { get; set; }
        public Nullable<System.DateTime> Time_Out { get; set; }
        public string Fuel_Status_In { get; set; }
        public string Fuel_Status_Out { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
