//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.RentalAgreements = new HashSet<RentalAgreement>();
        }
    
        public int Id { get; set; }
        public System.DateTime Modified_Time { get; set; }
        public System.DateTime Booking_Time { get; set; }
        public string Reserved_By { get; set; }
        public int Staff_Id { get; set; }
        public int Car_Id { get; set; }
        public int Client_Id { get; set; }
        public int Driver_Id { get; set; }
        public string Pick_Up_Address { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Client Client { get; set; }
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalAgreement> RentalAgreements { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
